/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Apriori.java
 *
 * Created on 29 Apr 16, 17:41:43
 */

package analisiperpus;

import Koneksi.connect;
import analisis.SQL;
import analisis.data;
import com.mysql.jdbc.Statement;
import sql.koneksi;
import java.sql.ResultSet;
import java.text.NumberFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
/**
 *
 * @author andra
 */
public class Apriori extends javax.swing.JFrame {

    Vector<data> dt=new Vector<data>();
    NumberFormat atur = NumberFormat.getInstance();

    /** Creates new form Apriori */
    public Apriori(java.awt.Frame parent, boolean modal) {
        
        initComponents();
        dataFromDataBaseToComboBox();
        setLocationRelativeTo(this);
        jTextField1.setText(String.valueOf(sql.bnyTransaksi()));
        //isidata();
        atur.setMaximumFractionDigits(2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelWarnaTransparan1 = new Tampilan.PanelWarnaTransparan();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panelWarnaTransparan2 = new Tampilan.PanelWarnaTransparan();
        jLabel5 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelWarnaTransparan3 = new Tampilan.PanelWarnaTransparan();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        button11 = new Tampilan.button1();
        cbxKategori = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuDaftarBuku = new javax.swing.JMenuItem();
        menuTambahBuku = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuDaftarTransaksi = new javax.swing.JMenuItem();
        menuTambahTransaksi = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuApriori = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analisis Apriori");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(74, 147, 221));

        panelWarnaTransparan1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Minimum Suport");

        jLabel3.setText("Nilai Minimum dari jumlah transaksi");

        jLabel4.setText("yang meminjam buku yang sama");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel13.setText("%");

        javax.swing.GroupLayout panelWarnaTransparan1Layout = new javax.swing.GroupLayout(panelWarnaTransparan1);
        panelWarnaTransparan1.setLayout(panelWarnaTransparan1Layout);
        panelWarnaTransparan1Layout.setHorizontalGroup(
            panelWarnaTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarnaTransparan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWarnaTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelWarnaTransparan1Layout.createSequentialGroup()
                        .addGroup(panelWarnaTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelWarnaTransparan1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinner1))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addComponent(jLabel4))
                .addContainerGap())
        );
        panelWarnaTransparan1Layout.setVerticalGroup(
            panelWarnaTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarnaTransparan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWarnaTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelWarnaTransparan2.setBackground(new java.awt.Color(51, 51, 51));
        panelWarnaTransparan2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Minimum Confidence");

        jLabel6.setText("Level minimum suatu tingkat kepercayaan");

        jLabel7.setText("antara suatu buku");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel11.setText("%");

        javax.swing.GroupLayout panelWarnaTransparan2Layout = new javax.swing.GroupLayout(panelWarnaTransparan2);
        panelWarnaTransparan2.setLayout(panelWarnaTransparan2Layout);
        panelWarnaTransparan2Layout.setHorizontalGroup(
            panelWarnaTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarnaTransparan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWarnaTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelWarnaTransparan2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap())
        );
        panelWarnaTransparan2Layout.setVerticalGroup(
            panelWarnaTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarnaTransparan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWarnaTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        panelWarnaTransparan3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setText("Count");

        jTextField1.setText("200");

        jLabel9.setText("Keseluruhan banyak");

        jLabel10.setText("suatu transaksi");

        javax.swing.GroupLayout panelWarnaTransparan3Layout = new javax.swing.GroupLayout(panelWarnaTransparan3);
        panelWarnaTransparan3.setLayout(panelWarnaTransparan3Layout);
        panelWarnaTransparan3Layout.setHorizontalGroup(
            panelWarnaTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarnaTransparan3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWarnaTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelWarnaTransparan3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap())
        );
        panelWarnaTransparan3Layout.setVerticalGroup(
            panelWarnaTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarnaTransparan3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelWarnaTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        button11.setText("Analisis");
        button11.setFont(new java.awt.Font("Tahoma", 1, 11));
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });

        cbxKategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semua Kategori" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(cbxKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(panelWarnaTransparan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(panelWarnaTransparan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addComponent(panelWarnaTransparan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(330, 330, 330))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelWarnaTransparan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelWarnaTransparan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelWarnaTransparan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(button11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(74, 147, 221));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ANALISIS POLA PEMINJAMAN BUKU DENGAN METODE APRIORI");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\andra\\Documents\\NetBeansProjects\\Pustaka\\src\\Tampilan\\logostmik.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                .addComponent(jLabel12))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jLabel1)))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jMenu1.setText("Buku");

        menuDaftarBuku.setText("Daftar Buku");
        menuDaftarBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDaftarBukuActionPerformed(evt);
            }
        });
        jMenu1.add(menuDaftarBuku);

        menuTambahBuku.setText("Tambah Buku");
        menuTambahBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTambahBukuActionPerformed(evt);
            }
        });
        jMenu1.add(menuTambahBuku);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");

        menuDaftarTransaksi.setText("Daftar Transaksi");
        menuDaftarTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDaftarTransaksiActionPerformed(evt);
            }
        });
        jMenu2.add(menuDaftarTransaksi);

        menuTambahTransaksi.setText("Tambah Transaksi");
        jMenu2.add(menuTambahTransaksi);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Analisis");

        menuApriori.setText("Apriori");
        menuApriori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAprioriActionPerformed(evt);
            }
        });
        jMenu3.add(menuApriori);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void menuDaftarBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDaftarBukuActionPerformed
        // TODO add your handling code here:
        new daftarBuku().show();
        dispose();
    }//GEN-LAST:event_menuDaftarBukuActionPerformed

    private void menuAprioriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAprioriActionPerformed
        // TODO add your handling code here:
        new Apriori(this, rootPaneCheckingEnabled).setVisible(true);

    }//GEN-LAST:event_menuAprioriActionPerformed

    private void menuDaftarTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDaftarTransaksiActionPerformed
        // TODO add your handling code here:
        new Transaksi().show();
        dispose();

    }//GEN-LAST:event_menuDaftarTransaksiActionPerformed

    private void menuTambahBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTambahBukuActionPerformed
        // TODO add your handling code here:
        new Buku().show();
        dispose();
    }//GEN-LAST:event_menuTambahBukuActionPerformed

    String k, sqlkat;
    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
        k = cbxKategori.getSelectedItem().toString();
        
        if (k == "Semua Kategori") {
            sqlkat = "SELECT kode_buku, count(no_transaksi) , judul_buku "+
                     "FROM tbl_transaksi_det GROUP BY kode_buku "+
                     "HAVING count( no_transaksi ) >=1 ";
        } else {
            sqlkat = "SELECT nama_kategori, kode_buku, count(no_transaksi) , judul_buku "+
                     "FROM tbl_transaksi_det WHERE nama_kategori = '"+k+"' GROUP BY kode_buku "+
                     "HAVING count( no_transaksi ) >=1 ";
        }
        
        dt.removeAllElements();
        try{
            int temp=Integer.parseInt(jTextField1.getText())*Integer.parseInt(jSpinner1.getValue().toString())/100;
            koneksi.konek();
            ResultSet set = koneksi.stat.executeQuery(sqlkat);
            while(set.next()){
                if(set.getInt("count(no_transaksi)")>=temp ){
                    data data=new data();
                    data.setKode_buku(set.getString("kode_buku"));
                    data.setJudul_buku(set.getString("judul_buku"));
                    data.setNilai(set.getInt("count(no_transaksi)"));
                    dt.add(data);
                }
            }
            set.close();
            koneksi.stat.close();
            koneksi.con.close();
        }
        catch(Exception z){}
        c2();
        c3();     
}//GEN-LAST:event_button11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Home().show();
        dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Apriori dialog = new Apriori(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
SQL sql=new SQL();
    koneksi koneksi=new koneksi();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Tampilan.button1 button11;
    private javax.swing.JComboBox cbxKategori;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem menuApriori;
    private javax.swing.JMenuItem menuDaftarBuku;
    private javax.swing.JMenuItem menuDaftarTransaksi;
    private javax.swing.JMenuItem menuTambahBuku;
    private javax.swing.JMenuItem menuTambahTransaksi;
    private Tampilan.PanelWarnaTransparan panelWarnaTransparan1;
    private Tampilan.PanelWarnaTransparan panelWarnaTransparan2;
    private Tampilan.PanelWarnaTransparan panelWarnaTransparan3;
    // End of variables declaration//GEN-END:variables

    public void dataFromDataBaseToComboBox(){
       try {
                Statement statement = (Statement)connect.GetConnection().createStatement();
                ResultSet res = statement.executeQuery
                        ("select * from tbl_kategori");
                while(res.next())
                {
                    cbxKategori.addItem(res.getString("nama_kategori"));
                }
                res.last();
            res.first();
            res.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Salah");
           }
    }

//     void isidata(){ }

    void c2(){
       jTextArea1.setText("");
       int n=0;
       float bnyAB, bnyA, bnyB=0;
       float supp,conf=0;

       for(int a=0; a<dt.size();a++){
           n++;
           for(int b=0+n; b<dt.size();b++){
               bnyAB=sql.c2(dt.get(a).getKode_buku(), dt.get(b).getKode_buku());
               bnyA=dt.get(a).getNilai();
               bnyB=dt.get(b).getNilai();
               supp=bnyAB/Integer.parseInt(jTextField1.getText())*100;
               if(supp>=Float.parseFloat(jSpinner1.getValue().toString())){
                    conf=(bnyAB/bnyA)*100;
                    if(conf>= Float.parseFloat(jSpinner2.getValue().toString()))
                    jTextArea1.setText(jTextArea1.getText()+" Jika meminjam buku \" "+dt.get(a).getJudul_buku()+" \" maka akan meminjam buku \" "+dt.get(b).getJudul_buku()+" \" dengan Supp  "+atur.format(supp)+"% dan Conf "+atur.format(conf)+"% \n");

                    conf=(bnyAB/bnyB)*100;
                    if(conf>= Float.parseFloat(jSpinner2.getValue().toString()))
                    jTextArea1.setText(jTextArea1.getText()+" Jika meminjam buku \" "+dt.get(b).getJudul_buku()+" \" maka akan meminjam buku \" "+dt.get(a).getJudul_buku()+" \" dengan Supp "+atur.format(supp)+"% dan Conf "+atur.format(conf)+"% \n");
               }
          }
       }
    }


      void c3(){
       int n=0,m=0,o=0;
       String item1,item2,item3="";
       float bnyABC,bnyAB=0;
       float supp,conf=0;
       for(int a=0; a<dt.size();a++){  n++;
           for(int b=0+n ;b<dt.size();b++){
               for(int c=0+b+1; c<dt.size();c++){
                   bnyABC=sql.c3(dt.get(a).getKode_buku(), dt.get(b).getKode_buku(), dt.get(c).getKode_buku());
                   supp=bnyABC/Integer.parseInt(jTextField1.getText())*100;

                   if(supp>=Float.parseFloat(jSpinner1.getValue().toString())){
                        bnyAB=sql.c2(dt.get(a).getKode_buku(), dt.get(b).getKode_buku());
                        conf=(bnyABC/bnyAB)*100;
                        if(conf>= Float.parseFloat(jSpinner2.getValue().toString()))
                        jTextArea1.setText(jTextArea1.getText()+" Jika meminjam buku \" "+dt.get(a).getJudul_buku()+" \" dan buku \" "+dt.get(b).getJudul_buku()+" \" maka akan meminjam buku \" "+dt.get(c).getJudul_buku()+" \" dengan Supp "+atur.format(supp)+"% dan Conf "+atur.format(conf)+"% \n");

                        bnyAB=sql.c2(dt.get(a).getKode_buku(), dt.get(c).getKode_buku());
                        conf=(bnyABC/bnyAB)*100;
                        if(conf>= Float.parseFloat(jSpinner2.getValue().toString()))
                        jTextArea1.setText(jTextArea1.getText()+" Jika meminjam buku \" "+dt.get(a).getJudul_buku()+" \" dan buku \" "+dt.get(c).getJudul_buku()+" \" maka akan meminjam buku \" "+dt.get(b).getJudul_buku()+" \" dengan Supp "+atur.format(supp)+"% dan Conf "+atur.format(conf)+"% \n");

                        bnyAB=sql.c2(dt.get(b).getKode_buku(), dt.get(c).getKode_buku());
                        conf=(bnyABC/bnyAB)*100;
                        if(conf>= Float.parseFloat(jSpinner2.getValue().toString()))
                        jTextArea1.setText(jTextArea1.getText()+" Jika meminjam buku \" "+dt.get(b).getJudul_buku()+" \" dan buku \" "+dt.get(c).getJudul_buku()+" \" maka akan meminjam buku \" "+dt.get(a).getJudul_buku()+" \" dengan Supp "+atur.format(supp)+"% dan Conf "+atur.format(conf)+"% \n");
                   }
               }
           }
       }
    }
}