/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Home.java
 *
 * Created on 09 Jun 16, 18:02:17
 */

package analisiperpus;

/**
 *
 * @author andra
 */
public class Home extends javax.swing.JFrame {

    /** Creates new form Home */
    public Home() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuDaftarBuku = new javax.swing.JMenuItem();
        menuTambahBuku = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuDaftarTransaksi = new javax.swing.JMenuItem();
        menuTambahTransaksi = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuApriori = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\andra\\Documents\\NetBeansProjects\\AnalisiPerpus\\src\\Tampilan\\brosur-dalam-logika.jpg")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1400, 850));

        jMenu1.setText("Buku");

        menuDaftarBuku.setText("Daftar Buku");
        menuDaftarBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDaftarBukuActionPerformed(evt);
            }
        });
        jMenu1.add(menuDaftarBuku);

        menuTambahBuku.setText("Tambah Buku");
        menuTambahBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTambahBukuActionPerformed(evt);
            }
        });
        jMenu1.add(menuTambahBuku);

        jMenuItem1.setText("Tambah Kategori");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");

        menuDaftarTransaksi.setText("Daftar Transaksi");
        menuDaftarTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDaftarTransaksiActionPerformed(evt);
            }
        });
        jMenu2.add(menuDaftarTransaksi);

        menuTambahTransaksi.setText("Tambah Transaksi");
        menuTambahTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTambahTransaksiActionPerformed(evt);
            }
        });
        jMenu2.add(menuTambahTransaksi);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Analisis");

        menuApriori.setText("Apriori");
        menuApriori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAprioriActionPerformed(evt);
            }
        });
        jMenu3.add(menuApriori);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(1881, 1881, 1881))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(579, 579, 579))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(jLabel1)
                .addContainerGap(404, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuTambahBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTambahBukuActionPerformed
        // TODO add your handling code here:
        new Buku().show();
        dispose();
    }//GEN-LAST:event_menuTambahBukuActionPerformed

    private void menuDaftarBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDaftarBukuActionPerformed
        // TODO add your handling code here:
        new daftarBuku().show();
        dispose();
    }//GEN-LAST:event_menuDaftarBukuActionPerformed

    private void menuDaftarTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDaftarTransaksiActionPerformed
        // TODO add your handling code here:
        new Transaksi().show();
        dispose();
    }//GEN-LAST:event_menuDaftarTransaksiActionPerformed

    private void menuTambahTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTambahTransaksiActionPerformed
        // TODO add your handling code here:
        new bukuPinjam().show();
        dispose();
    }//GEN-LAST:event_menuTambahTransaksiActionPerformed

    private void menuAprioriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAprioriActionPerformed
        // TODO add your handling code here:
        new Apriori(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_menuAprioriActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new Kategori().show();
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuApriori;
    private javax.swing.JMenuItem menuDaftarBuku;
    private javax.swing.JMenuItem menuDaftarTransaksi;
    private javax.swing.JMenuItem menuTambahBuku;
    private javax.swing.JMenuItem menuTambahTransaksi;
    // End of variables declaration//GEN-END:variables

}
